//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace YassakoPortalLogic.liveutilityapi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="YakakoUtilityApiSoap", Namespace="http://yassakoutilityapi/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Credentials))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Error))]
    public partial class YakakoUtilityApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryCustomerDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakeUtilityPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTranStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUtilityBalanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public YakakoUtilityApi() {
            this.Url = global::YassakoPortalLogic.Properties.Settings.Default.YassakoPortalLogic_liveutilityapi_YakakoUtilityApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryCustomerDetailsCompletedEventHandler QueryCustomerDetailsCompleted;
        
        /// <remarks/>
        public event MakeUtilityPaymentCompletedEventHandler MakeUtilityPaymentCompleted;
        
        /// <remarks/>
        public event GetTranStatusCompletedEventHandler GetTranStatusCompleted;
        
        /// <remarks/>
        public event GetUtilityBalanceCompletedEventHandler GetUtilityBalanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yassakoutilityapi/QueryCustomerDetails", RequestNamespace="http://yassakoutilityapi/", ResponseNamespace="http://yassakoutilityapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public QueryCustomerDetailResponse QueryCustomerDetails(QueryCustomerDetailRequest req) {
            object[] results = this.Invoke("QueryCustomerDetails", new object[] {
                        req});
            return ((QueryCustomerDetailResponse)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCustomerDetailsAsync(QueryCustomerDetailRequest req) {
            this.QueryCustomerDetailsAsync(req, null);
        }
        
        /// <remarks/>
        public void QueryCustomerDetailsAsync(QueryCustomerDetailRequest req, object userState) {
            if ((this.QueryCustomerDetailsOperationCompleted == null)) {
                this.QueryCustomerDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCustomerDetailsOperationCompleted);
            }
            this.InvokeAsync("QueryCustomerDetails", new object[] {
                        req}, this.QueryCustomerDetailsOperationCompleted, userState);
        }
        
        private void OnQueryCustomerDetailsOperationCompleted(object arg) {
            if ((this.QueryCustomerDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCustomerDetailsCompleted(this, new QueryCustomerDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yassakoutilityapi/MakeUtilityPayment", RequestNamespace="http://yassakoutilityapi/", ResponseNamespace="http://yassakoutilityapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentResponse MakeUtilityPayment(PaymentRequest req) {
            object[] results = this.Invoke("MakeUtilityPayment", new object[] {
                        req});
            return ((PaymentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void MakeUtilityPaymentAsync(PaymentRequest req) {
            this.MakeUtilityPaymentAsync(req, null);
        }
        
        /// <remarks/>
        public void MakeUtilityPaymentAsync(PaymentRequest req, object userState) {
            if ((this.MakeUtilityPaymentOperationCompleted == null)) {
                this.MakeUtilityPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakeUtilityPaymentOperationCompleted);
            }
            this.InvokeAsync("MakeUtilityPayment", new object[] {
                        req}, this.MakeUtilityPaymentOperationCompleted, userState);
        }
        
        private void OnMakeUtilityPaymentOperationCompleted(object arg) {
            if ((this.MakeUtilityPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakeUtilityPaymentCompleted(this, new MakeUtilityPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yassakoutilityapi/GetTranStatus", RequestNamespace="http://yassakoutilityapi/", ResponseNamespace="http://yassakoutilityapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetTranStatusResponse GetTranStatus(GetTranStatusReq req) {
            object[] results = this.Invoke("GetTranStatus", new object[] {
                        req});
            return ((GetTranStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTranStatusAsync(GetTranStatusReq req) {
            this.GetTranStatusAsync(req, null);
        }
        
        /// <remarks/>
        public void GetTranStatusAsync(GetTranStatusReq req, object userState) {
            if ((this.GetTranStatusOperationCompleted == null)) {
                this.GetTranStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTranStatusOperationCompleted);
            }
            this.InvokeAsync("GetTranStatus", new object[] {
                        req}, this.GetTranStatusOperationCompleted, userState);
        }
        
        private void OnGetTranStatusOperationCompleted(object arg) {
            if ((this.GetTranStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTranStatusCompleted(this, new GetTranStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yassakoutilityapi/GetUtilityBalance", RequestNamespace="http://yassakoutilityapi/", ResponseNamespace="http://yassakoutilityapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CheckBalanceResponse GetUtilityBalance(CheckBalanceRequest request) {
            object[] results = this.Invoke("GetUtilityBalance", new object[] {
                        request});
            return ((CheckBalanceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUtilityBalanceAsync(CheckBalanceRequest request) {
            this.GetUtilityBalanceAsync(request, null);
        }
        
        /// <remarks/>
        public void GetUtilityBalanceAsync(CheckBalanceRequest request, object userState) {
            if ((this.GetUtilityBalanceOperationCompleted == null)) {
                this.GetUtilityBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUtilityBalanceOperationCompleted);
            }
            this.InvokeAsync("GetUtilityBalance", new object[] {
                        request}, this.GetUtilityBalanceOperationCompleted, userState);
        }
        
        private void OnGetUtilityBalanceOperationCompleted(object arg) {
            if ((this.GetUtilityBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUtilityBalanceCompleted(this, new GetUtilityBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class QueryCustomerDetailRequest {
        
        private string meterNoField;
        
        private string customerTelField;
        
        private string vendorcodeField;
        
        private string utilityCodeField;
        
        private string passwordField;
        
        /// <remarks/>
        public string MeterNo {
            get {
                return this.meterNoField;
            }
            set {
                this.meterNoField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTel {
            get {
                return this.customerTelField;
            }
            set {
                this.customerTelField = value;
            }
        }
        
        /// <remarks/>
        public string Vendorcode {
            get {
                return this.vendorcodeField;
            }
            set {
                this.vendorcodeField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityCode {
            get {
                return this.utilityCodeField;
            }
            set {
                this.utilityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckBalanceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTranStatusReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class Credentials {
        
        private string vendorCodeField;
        
        private string passwordField;
        
        /// <remarks/>
        public string VendorCode {
            get {
                return this.vendorCodeField;
            }
            set {
                this.vendorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class CheckBalanceRequest : Credentials {
        
        private string utilityCodeField;
        
        /// <remarks/>
        public string UtilityCode {
            get {
                return this.utilityCodeField;
            }
            set {
                this.utilityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class GetTranStatusReq : Credentials {
        
        private string tranIdField;
        
        private string utilityCodeField;
        
        /// <remarks/>
        public string TranId {
            get {
                return this.tranIdField;
            }
            set {
                this.tranIdField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityCode {
            get {
                return this.utilityCodeField;
            }
            set {
                this.utilityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class PaymentRequest : Credentials {
        
        private string customerNameField;
        
        private string customerRefField;
        
        private string customerTelField;
        
        private string tranIdField;
        
        private string tranAmountField;
        
        private string paymentDateField;
        
        private string utilityCodeField;
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerRef {
            get {
                return this.customerRefField;
            }
            set {
                this.customerRefField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTel {
            get {
                return this.customerTelField;
            }
            set {
                this.customerTelField = value;
            }
        }
        
        /// <remarks/>
        public string TranId {
            get {
                return this.tranIdField;
            }
            set {
                this.tranIdField = value;
            }
        }
        
        /// <remarks/>
        public string TranAmount {
            get {
                return this.tranAmountField;
            }
            set {
                this.tranAmountField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityCode {
            get {
                return this.utilityCodeField;
            }
            set {
                this.utilityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class Customer {
        
        private string idField;
        
        private string crtonField;
        
        private string crtbyField;
        
        private string mdfonField;
        
        private string mdfbyField;
        
        private string usernameField;
        
        private string identityidField;
        
        private string passwordField;
        
        private string customertypeField;
        
        private string statusField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string sexField;
        
        private string telField;
        
        private string mobileField;
        
        private string emailField;
        
        private string addressField;
        
        private string postcodeField;
        
        private string maxAmountToBorrowField;
        
        private string custBalanceField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string crton {
            get {
                return this.crtonField;
            }
            set {
                this.crtonField = value;
            }
        }
        
        /// <remarks/>
        public string crtby {
            get {
                return this.crtbyField;
            }
            set {
                this.crtbyField = value;
            }
        }
        
        /// <remarks/>
        public string mdfon {
            get {
                return this.mdfonField;
            }
            set {
                this.mdfonField = value;
            }
        }
        
        /// <remarks/>
        public string mdfby {
            get {
                return this.mdfbyField;
            }
            set {
                this.mdfbyField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string identityid {
            get {
                return this.identityidField;
            }
            set {
                this.identityidField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string customertype {
            get {
                return this.customertypeField;
            }
            set {
                this.customertypeField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string MaxAmountToBorrow {
            get {
                return this.maxAmountToBorrowField;
            }
            set {
                this.maxAmountToBorrowField = value;
            }
        }
        
        /// <remarks/>
        public string CustBalance {
            get {
                return this.custBalanceField;
            }
            set {
                this.custBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class Meter {
        
        private string idField;
        
        private string crtonField;
        
        private string meterNoField;
        
        private string crtbyField;
        
        private string mdfonField;
        
        private string mdfbyField;
        
        private string msnoField;
        
        private string assetnoField;
        
        private string descrField;
        
        private string metertype_idField;
        
        private string statusField;
        
        private string krnField;
        
        private string tiField;
        
        private string kenField;
        
        private string sgcField;
        
        private string collectidField;
        
        private string deviceidField;
        
        private string loanLimitField;
        
        private string lastvendingField;
        
        private string lastfeevendingField;
        
        private string currentmonthunitsField;
        
        private string currentmonthmoneyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string crton {
            get {
                return this.crtonField;
            }
            set {
                this.crtonField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNo {
            get {
                return this.meterNoField;
            }
            set {
                this.meterNoField = value;
            }
        }
        
        /// <remarks/>
        public string crtby {
            get {
                return this.crtbyField;
            }
            set {
                this.crtbyField = value;
            }
        }
        
        /// <remarks/>
        public string mdfon {
            get {
                return this.mdfonField;
            }
            set {
                this.mdfonField = value;
            }
        }
        
        /// <remarks/>
        public string mdfby {
            get {
                return this.mdfbyField;
            }
            set {
                this.mdfbyField = value;
            }
        }
        
        /// <remarks/>
        public string msno {
            get {
                return this.msnoField;
            }
            set {
                this.msnoField = value;
            }
        }
        
        /// <remarks/>
        public string assetno {
            get {
                return this.assetnoField;
            }
            set {
                this.assetnoField = value;
            }
        }
        
        /// <remarks/>
        public string descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <remarks/>
        public string metertype_id {
            get {
                return this.metertype_idField;
            }
            set {
                this.metertype_idField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string krn {
            get {
                return this.krnField;
            }
            set {
                this.krnField = value;
            }
        }
        
        /// <remarks/>
        public string ti {
            get {
                return this.tiField;
            }
            set {
                this.tiField = value;
            }
        }
        
        /// <remarks/>
        public string ken {
            get {
                return this.kenField;
            }
            set {
                this.kenField = value;
            }
        }
        
        /// <remarks/>
        public string sgc {
            get {
                return this.sgcField;
            }
            set {
                this.sgcField = value;
            }
        }
        
        /// <remarks/>
        public string collectid {
            get {
                return this.collectidField;
            }
            set {
                this.collectidField = value;
            }
        }
        
        /// <remarks/>
        public string deviceid {
            get {
                return this.deviceidField;
            }
            set {
                this.deviceidField = value;
            }
        }
        
        /// <remarks/>
        public string loanLimit {
            get {
                return this.loanLimitField;
            }
            set {
                this.loanLimitField = value;
            }
        }
        
        /// <remarks/>
        public string lastvending {
            get {
                return this.lastvendingField;
            }
            set {
                this.lastvendingField = value;
            }
        }
        
        /// <remarks/>
        public string lastfeevending {
            get {
                return this.lastfeevendingField;
            }
            set {
                this.lastfeevendingField = value;
            }
        }
        
        /// <remarks/>
        public string currentmonthunits {
            get {
                return this.currentmonthunitsField;
            }
            set {
                this.currentmonthunitsField = value;
            }
        }
        
        /// <remarks/>
        public string currentmonthmoney {
            get {
                return this.currentmonthmoneyField;
            }
            set {
                this.currentmonthmoneyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckBalanceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTranStatusResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryCustomerDetailResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class Error {
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        /// <remarks/>
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class CheckBalanceResponse : Error {
        
        private string utilityBalanceField;
        
        private string utilityCommBalanceField;
        
        private string utilityField;
        
        /// <remarks/>
        public string UtilityBalance {
            get {
                return this.utilityBalanceField;
            }
            set {
                this.utilityBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityCommBalance {
            get {
                return this.utilityCommBalanceField;
            }
            set {
                this.utilityCommBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string Utility {
            get {
                return this.utilityField;
            }
            set {
                this.utilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTranStatusResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class PaymentResponse : Error {
        
        private string utilityRefField;
        
        private string utilityIdField;
        
        private string reasonField;
        
        private string narrationField;
        
        private string narration1Field;
        
        private string narration2Field;
        
        private string narration3Field;
        
        private string narration4Field;
        
        private string narration5Field;
        
        /// <remarks/>
        public string UtilityRef {
            get {
                return this.utilityRefField;
            }
            set {
                this.utilityRefField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityId {
            get {
                return this.utilityIdField;
            }
            set {
                this.utilityIdField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public string Narration {
            get {
                return this.narrationField;
            }
            set {
                this.narrationField = value;
            }
        }
        
        /// <remarks/>
        public string Narration1 {
            get {
                return this.narration1Field;
            }
            set {
                this.narration1Field = value;
            }
        }
        
        /// <remarks/>
        public string Narration2 {
            get {
                return this.narration2Field;
            }
            set {
                this.narration2Field = value;
            }
        }
        
        /// <remarks/>
        public string Narration3 {
            get {
                return this.narration3Field;
            }
            set {
                this.narration3Field = value;
            }
        }
        
        /// <remarks/>
        public string Narration4 {
            get {
                return this.narration4Field;
            }
            set {
                this.narration4Field = value;
            }
        }
        
        /// <remarks/>
        public string Narration5 {
            get {
                return this.narration5Field;
            }
            set {
                this.narration5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class GetTranStatusResponse : PaymentResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yassakoutilityapi/")]
    public partial class QueryCustomerDetailResponse : Error {
        
        private string snField;
        
        private string meterTypeField;
        
        private string meterNoField;
        
        private Meter meterField;
        
        private Customer customerField;
        
        /// <remarks/>
        public string sn {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        public string meterType {
            get {
                return this.meterTypeField;
            }
            set {
                this.meterTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNo {
            get {
                return this.meterNoField;
            }
            set {
                this.meterNoField = value;
            }
        }
        
        /// <remarks/>
        public Meter meter {
            get {
                return this.meterField;
            }
            set {
                this.meterField = value;
            }
        }
        
        /// <remarks/>
        public Customer customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void QueryCustomerDetailsCompletedEventHandler(object sender, QueryCustomerDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCustomerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCustomerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryCustomerDetailResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryCustomerDetailResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void MakeUtilityPaymentCompletedEventHandler(object sender, MakeUtilityPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakeUtilityPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakeUtilityPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetTranStatusCompletedEventHandler(object sender, GetTranStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTranStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTranStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetTranStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetTranStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetUtilityBalanceCompletedEventHandler(object sender, GetUtilityBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUtilityBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUtilityBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckBalanceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckBalanceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591